### ISSUE TITLE
Suggestion

### ISSUE THREAD

**Issue by ndonkoHenri** [JorgeAlvarez21/Fletdev_Mobile_App_Tracker#1]
Hey. Just from seeing this. It looks really awesome. 👏🏽 
To attract the Flet audience/users to your project, I will suggest you post them in Flet's discord server(project showcase area).
Let me know if you need a link to hop in.
Another way is by opening a discussion (category=show-and-tell) in Flet's repo.

Don't keep such an interesting project under the hood!Show it to the world.
Let me know what you think of my ideas.

**Comment by JorgeAlvarez21** [comment]
Hey thanks for the shout out!
That's a great idea, I didn't know there was a Flet discord server but of course I'd be happy share some of my own. There are not many projects out there using the framework as of yet, I'm thrilled to see what other users have shared as well.

Please post the link
